services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: surveydbuser
      POSTGRES_PASSWORD: surveydbpass
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    depends_on:
      - db
    environment:
      - DB_USER=surveydbuser
      - DB_PASSWORD=surveydbpass
      - DB_NAME=survey_db
      - DB_HOST=db
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Монтируем локальную директорию для горячей перезагрузки кода

volumes:
  postgres_data:
