/* eslint-disable */
import type { ISurvey } from "@widget/Survey.types";

(globalThis as any).mockSurvey = {
  id: 1,
  title: "Опрос о клиентской обратной связи",
  active: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  questions: [
    {
      id: 101,
      order: 1,
      required: true,
      type: "single",
      title: "Как вы узнали о нас?",
      options: ["Социальные сети", "Друзья", "Google", "Другое"],
    },
    {
      id: 102,
      order: 2,
      required: true,
      type: "multi",
      title: "Какими функциями вы пользуетесь?",
      options: [
        "Панель управления",
        "Отчеты",
        "Оповещения",
        "Интеграции",
        "Интеграции",
        "Интеграции",
        "Интеграции",
        "Панель управления",
        "Отчеты",
        "Оповещения",
        "Интеграции",
        "Интеграции",
        "Интеграции",
        "Интеграции",
      ],
    },
    {
      id: 1073,
      order: 63,
      required: true,
      type: "dropdown",
      title: "Какими функциями вы пользуетесь?",
      options: ["Панель управления", "Отчеты", "Оповещения", "Интеграции"],
    },
    {
      id: 103,
      order: 3,
      required: true,
      type: "binary",
      title: "Вы бы порекомендовали нас?",
      description: "А шо вы тут делаете?",
    },
    {
      id: 104,
      order: 4,
      required: true,
      type: "text",
      title: "Ваше имя",
    },
    {
      id: 105,
      order: 5,
      required: false,
      type: "textarea",
      title: "Есть ли у вас предложения или отзывы?",
    },
    {
      id: 106,
      order: 6,
      required: false,
      type: "date",
      title: "Дата вашего последнего визита",
    },
  ],
  welcomeScreen: {
    active: true,
    hint: "Мы хотим узнать ваше мнение",
    title: "Добро пожаловать!",
    description: "Мы ценим ваше время. Пожалуйста, пройдите небольшой опрос.",
    button_text: "Начать опрос",
    legal_info: "Ваши ответы анонимны.",
    design_settings: {
      image_url: "https://cs5.pikabu.ru/post_img/big/2015/06/04/11/1433446202_1725992411.jpg",
      layout: "with_image",
      alignment: "center",
    },
  },
  personalScreen: {
    active: true,
    title: "Расскажите о себе",
    description: "Мы собираем минимальные личные данные.",
    button_text: "Отправить информацию",
    personal_fields: [
      {
        type: "name",
        required: true,
        label: "Полное имя",
        placeholder: "Введите ваше имя",
      },
      {
        type: "email",
        required: true,
        label: "Электронная почта",
        placeholder: "ваш@email.com",
      },
      {
        type: "phone",
        required: true,
        label: "Телефон",
        placeholder: "+7 (___) ___-__-__",
      },
    ],
    design_settings: {
      image_url: "https://cs5.pikabu.ru/post_img/big/2015/06/04/11/1433446202_1725992411.jpg",
      layout: "image_background",
      alignment: "left",
    },
  },
  completionScreen: {
    active: true,
    title: "Спасибо!",
    description: "Ваш отзыв был отправлен.",
    button_text: "Перейти на главную",
    button_url: "https://example.com",
    design_settings: {
      image_url: "https://img.freepik.com/premium-photo/premium-quality-background-texture_599236-376.jpg",
      layout: "image_background",
      alignment: "center",
    },
  },
  design_settings: {
    placement: "inbuilt",
    width: 100,
    width_unit: "%",
    height: 400,
    height_unit: "px",
    background_color: "#ffffff",
    text_color: "#222222",
    button_color: "#20A050",
    font_family: "Inter",
    borderRadius: [12, 12, 12, 12],
    margin: [0, 0, 0, 0],
    padding: [24, 24, 24, 24],
  },
  display_settings: {
    target_id: "app",
    block_scroll: true,
    prevent_repeat: false,
    timer_sec: 1000,
    url_match_mode: "contains",
    url_pattern: ["*"],
  },
  responses: [],
  statistics: {
    responsesCount: 0,
    completionRate: 0,
    averageTimeSec: 0,
  },
} as ISurvey;
