import { ISurvey } from "./widget/Survey.types";

const mockSurvey: ISurvey = {
  id: 1,
  title: "Customer Feedback Survey",
  active: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  questions: [
    {
      id: 101,
      order: 1,
      required: true,
      type: "single",
      title: "How did you hear about us?",
      options: ["Social Media", "Friends", "Google", "Other"],
    },
    {
      id: 102,
      order: 2,
      required: true,
      type: "multi",
      title: "What features do you use?",
      options: ["Dashboard", "Reports", "Alerts", "Integrations"],
    },
    {
      id: 103,
      order: 3,
      required: false,
      type: "binary",
      title: "Would you recommend us?",
    },
    {
      id: 104,
      order: 4,
      required: true,
      type: "text",
      title: "Your Name",
    },
    {
      id: 105,
      order: 5,
      required: false,
      type: "textarea",
      title: "Any suggestions or feedback?",
    },
    {
      id: 106,
      order: 6,
      required: false,
      type: "date",
      title: "Date of your last visit",
    },
  ],
  welcomeScreen: {
    active: true,
    title: "Welcome!",
    description: "We appreciate your time. Please take a short survey.",
    button_text: "Start Survey",
    legal_info: "Your responses are anonymous.",
    design_settings: {
      layout: "without_image",
      alignment: "center",
    },
  },
  personalScreen: {
    active: true,
    title: "Tell us about yourself",
    description: "We collect minimal personal data.",
    button_text: "Submit Info",
    personal_fields: [
      {
        type: "name",
        required: true,
        label: "Full Name",
        placeholder: "Enter your name",
      },
      {
        type: "email",
        required: true,
        label: "Email",
        placeholder: "your@email.com",
      },
      {
        type: "phone",
        required: false,
        label: "Phone",
        placeholder: "+7 (___) ___-__-__",
      },
    ],
    design_settings: {
      layout: "without_image",
      alignment: "left",
    },
  },
  completionScreen: {
    active: true,
    title: "Thank you!",
    description: "Your feedback has been submitted.",
    button_text: "Go to homepage",
    button_url: "https://example.com",
    design_settings: {
      layout: "without_image",
      alignment: "center",
    },
  },
  design_settings: {
    placement: "inbuilt",
    width: 400,
    width_unit: "px",
    height: 600,
    height_unit: "px",
    background_color: "#ffffff",
    text_color: "#222222",
    button_color: "#4CAF50",
    font_family: "Inter",
    borderRadius: [12, 12, 12, 12],
    margin: [0, 0, 0, 0],
    padding: [24, 24, 24, 24],
  },
  display_settings: {
    target_id: "survey-container",
    block_scroll: false,
    prevent_repeat: false,
    timer_sec: 0,
    url_match_mode: "contains",
    url_pattern: ["*"],
  },
  responses: [],
  statistics: {
    responsesCount: 0,
    completionRate: 0,
    averageTimeSec: 0,
  },
};

export default mockSurvey;
